// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package injector

import (
	"github.com/gomaglev/microshop/v1/internal/app/model/gorm/model"
	"github.com/gomaglev/microshop/v1/internal/app/service"
	"github.com/gomaglev/microshop/v1/internal/app/service/order/item/v1"
	"github.com/gomaglev/microshop/v1/internal/app/service/order/v1"
	"github.com/gomaglev/microshop/v1/internal/pkg/server/rpc"
)

// Injectors from wire.go:

func BuildInjector() (*Injector, func(), error) {
	db, cleanup, err := InitGormDB()
	if err != nil {
		return nil, nil, err
	}
	orderItem := &model.OrderItem{
		DB: db,
	}
	itemService := &item.ItemService{
		ItemModel: orderItem,
	}
	modelOrder := &model.Order{
		DB: db,
	}
	orderService := &order.OrderService{
		OrderModel: modelOrder,
	}
	register := &service.Register{
		ItemService:  itemService,
		OrderService: orderService,
	}
	limiter := InitGrpcLimiter()
	server := &rpc.Server{
		Register: register,
		Limiter:  limiter,
	}
	gateway := &rpc.Gateway{
		Register: register,
	}
	injector := &Injector{
		Server:  server,
		Gateway: gateway,
	}
	return injector, func() {
		cleanup()
	}, nil
}
