// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package injector

import (
	"github.com/gomaglev/microshop/internal/app/model/gorm/model"
	"github.com/gomaglev/microshop/internal/app/service"
	"github.com/gomaglev/microshop/internal/app/service/v1/order"
	"github.com/gomaglev/microshop/internal/app/service/v1/order/item"
	order2 "github.com/gomaglev/microshop/internal/app/service/v2/order"
	item2 "github.com/gomaglev/microshop/internal/app/service/v2/order/item"
	"github.com/gomaglev/microshop/internal/pkg/server/rpc"
)

// Injectors from wire.go:

func BuildInjector() (*Injector, func(), error) {
	db, cleanup, err := InitGormDB()
	if err != nil {
		return nil, nil, err
	}
	orderItem := &model.OrderItem{
		DB: db,
	}
	itemService := &item.ItemService{
		ItemModel: orderItem,
	}
	modelOrder := &model.Order{
		DB: db,
	}
	orderService := &order.OrderService{
		OrderModel: modelOrder,
	}
	itemItemService := &item2.ItemService{
		ItemModel: orderItem,
	}
	orderOrderService := &order2.OrderService{
		OrderModel: modelOrder,
	}
	register := &service.Register{
		ItemServiceV1:  itemService,
		OrderServiceV1: orderService,
		ItemServiceV2:  itemItemService,
		OrderServiceV2: orderOrderService,
	}
	limiter := InitGrpcLimiter()
	server := &rpc.Server{
		Register: register,
		Limiter:  limiter,
	}
	gateway := &rpc.Gateway{
		Register: register,
	}
	injector := &Injector{
		Server:  server,
		Gateway: gateway,
	}
	return injector, func() {
		cleanup()
	}, nil
}
