// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: pkg/proto/order/item/message/types.proto

package message

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _types_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on OrderItemMessage with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *OrderItemMessage) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for Message

	// no validation rules for ItemId

	if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OrderItemMessageValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OrderItemMessageValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// OrderItemMessageValidationError is the validation error returned by
// OrderItemMessage.Validate if the designated constraints aren't met.
type OrderItemMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrderItemMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrderItemMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrderItemMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrderItemMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrderItemMessageValidationError) ErrorName() string { return "OrderItemMessageValidationError" }

// Error satisfies the builtin error interface
func (e OrderItemMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrderItemMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrderItemMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrderItemMessageValidationError{}

// Validate checks the field values on OrderItemMessages with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *OrderItemMessages) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return OrderItemMessagesValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OrderItemMessagesValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// OrderItemMessagesValidationError is the validation error returned by
// OrderItemMessages.Validate if the designated constraints aren't met.
type OrderItemMessagesValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrderItemMessagesValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrderItemMessagesValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrderItemMessagesValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrderItemMessagesValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrderItemMessagesValidationError) ErrorName() string {
	return "OrderItemMessagesValidationError"
}

// Error satisfies the builtin error interface
func (e OrderItemMessagesValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrderItemMessages.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrderItemMessagesValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrderItemMessagesValidationError{}
